CREATE DATABASE IF NOT EXISTS accounts;

CREATE TABLE IF NOT EXISTS users (
    ID_user INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    passwd VARCHAR(64) NOT NULL
);